# Generated by Django 4.0 on 2021-12-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_orderitem_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_option',
        ),
    ]
